version: "3.9"
services:
  app:
    build: .
    container_name: php82-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=dev
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app
      - DB_USER=app
      - DB_PASS=secret
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres14
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
